version: 2.1

orbs:
  ruby: circleci/ruby@1.1.1
  node: circleci/node@4.0.0
  browser-tools: circleci/browser-tools@1.0.1

jobs:
  build:
    docker:
      - image: circleci/node:12.13-stretch-browsers
      - image: circleci/ruby:2.6.3-stretch-node
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
    steps:
      - checkout
      - ruby/install-deps:
          bundler-version: 1.17.2
      - node/install-packages: 
          pkg-manager: yarn

  test:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
      - image: circleci/postgres:11.7
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: todo_dockerize_test
          POSTGRES_HOST_AUTH_METHOD: trust
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: circleci
      PGPASSWORD: ""
      TZ: "/usr/share/zoneinfo/Asia/Tokyo"
      RAILS_ENV: test

    steps:
      - checkout
      - ruby/install-deps:
          bundler-version: 2.1.4
      - node/install-packages: 
          pkg-manager: yarn
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: DB Initializing
          command: |
            dockerize -wait tcp://localhost:5432 -timeout 1m
            bundle exec rake db:schema:load
      - run:
          name: rspec
          command: |
            bundle exec rspec --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format documentation
      - store_test_results:
          path: test_results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build